"""Add all indexes

Revision ID: 119bc53d93a1
Revises: f207937b02ac
Create Date: 2025-05-21 14:57:48.037237

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '119bc53d93a1'
down_revision: Union[str, None] = 'f207937b02ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_flashcards_next_review', 'flashcards', ['next_review'], unique=False)
    op.create_index('idx_flashcards_status', 'flashcards', ['status'], unique=False)
    op.create_index('idx_learning_projects_category', 'learning_projects', ['category'], unique=False)
    op.create_index('idx_learning_projects_status', 'learning_projects', ['status'], unique=False)
    op.create_index('idx_notes_category', 'notes', ['category'], unique=False)
    op.create_index('idx_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_sessions_learning_project_id', 'sessions', ['learning_project_id'], unique=False)
    op.create_index('idx_sessions_start_time', 'sessions', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_start_time', table_name='sessions')
    op.drop_index('idx_sessions_learning_project_id', table_name='sessions')
    op.drop_index('idx_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_index('idx_notes_category', table_name='notes')
    op.drop_index('idx_learning_projects_status', table_name='learning_projects')
    op.drop_index('idx_learning_projects_category', table_name='learning_projects')
    op.drop_index('idx_flashcards_status', table_name='flashcards')
    op.drop_index('idx_flashcards_next_review', table_name='flashcards')
    # ### end Alembic commands ###
