"""Add user_id to notes table

Revision ID: 49dcf2d5c5e4
Revises: b79968a4bf2c
Create Date: 2025-05-25 16:42:36.774580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49dcf2d5c5e4"
down_revision: Union[str, None] = "b79968a4bf2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_categories_name", table_name="categories")
    op.create_index("idx_categories_name", "categories", ["name"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_index(
        op.f("ix_learning_projects_category_id"),
        "learning_projects",
        ["category_id"],
        unique=False,
    )
    op.add_column("notes", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.create_foreign_key(None, "notes", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_column("notes", "user_id")
    op.drop_index(
        op.f("ix_learning_projects_category_id"), table_name="learning_projects"
    )
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index("idx_categories_name", table_name="categories")
    op.create_index("idx_categories_name", "categories", ["name"], unique=True)
    # ### end Alembic commands ###
