"""Add learning projects and update session model

Revision ID: f207937b02ac
Revises: f5d337fffcb3
Create Date: 2025-05-21 14:55:24.728346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f207937b02ac"
down_revision: Union[str, None] = "f5d337fffcb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_projects_user_id"),
        "learning_projects",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "sessions", sa.Column("learning_project_id", sa.Uuid(), nullable=True)
    )
    op.add_column("sessions", sa.Column("actual_duration", sa.Integer(), nullable=True))
    op.add_column(
        "sessions", sa.Column("session_type", sa.String(length=20), nullable=False)
    )
    op.create_index(
        op.f("ix_sessions_learning_project_id"),
        "sessions",
        ["learning_project_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "sessions", "learning_projects", ["learning_project_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_index(op.f("ix_sessions_learning_project_id"), table_name="sessions")
    op.drop_column("sessions", "session_type")
    op.drop_column("sessions", "actual_duration")
    op.drop_column("sessions", "learning_project_id")
    op.drop_index(op.f("ix_learning_projects_user_id"), table_name="learning_projects")
    op.drop_table("learning_projects")
    # ### end Alembic commands ###
